version: '3.8'

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    env_file:
      - .env
    depends_on:
      - redis
    restart: always
  redis-dev:
    image: redis:latest
    container_name: redis
    ports:
      - 6379
    volumes:
      - redis_data:/data # Persist data
    command: redis-server --requirepass comic24 --bind 0.0.0.0 --port 6379
    restart: unless-stopped
volumes:
  redis_data:
